"""Deriving fix.files and fix.symbols from the fix commit (plan.md section 3.3)."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from segbench.corpus.derive import (
    DerivedFix,
    DeriveError,
    derive_fix,
    go_symbols,
    python_symbols,
    write_derived_fix,
)


def test_derive_reports_every_changed_file(fix_repo: Path) -> None:
    derived = derive_fix(fix_repo, "HEAD")

    assert derived.files == ["README.md", "main.go", "pkg/mod.py"]


def test_derive_reports_only_the_changed_symbols(fix_repo: Path) -> None:
    derived = derive_fix(fix_repo, "HEAD")

    assert derived.symbols == ["Driver.stop", "Server.Handle"]


def test_derive_resolves_the_ref_to_a_full_hash(fix_repo: Path) -> None:
    derived = derive_fix(fix_repo, "HEAD")

    assert len(derived.commit) == 40


def test_derive_rejects_a_directory_that_is_not_a_repository(tmp_path: Path) -> None:
    with pytest.raises(DeriveError, match="not a git repository"):
        derive_fix(tmp_path, "HEAD")


def test_derive_rejects_an_unknown_commit(fix_repo: Path) -> None:
    with pytest.raises(DeriveError, match="rev-parse"):
        derive_fix(fix_repo, "does-not-exist")


# --- Python symbol extraction --------------------------------------------------------------


PY_SOURCE = """\
import os


def module_level():
    return 1


class Driver:
    def start(self):
        return 2

    @property
    def name(self):
        return "d"
"""


@pytest.mark.parametrize(
    ("line", "expected"),
    [
        (5, ["module_level"]),
        (10, ["Driver.start"]),
        (14, ["Driver.name"]),
        (1, []),
    ],
)
def test_python_symbols_covering_a_changed_line(line: int, expected: list[str]) -> None:
    assert python_symbols(PY_SOURCE, {line}) == expected


def test_python_decorator_line_belongs_to_its_function() -> None:
    assert python_symbols(PY_SOURCE, {12}) == ["Driver.name"]


def test_python_reports_the_method_rather_than_its_enclosing_class() -> None:
    """`Driver.start` is the answer the grader's symbol_hit wants; `Driver` alone is noise."""
    assert python_symbols(PY_SOURCE, {10}) == ["Driver.start"]


def test_python_unparseable_source_yields_no_symbols_rather_than_failing() -> None:
    assert python_symbols("def broken(:\n", {1}) == []


# --- Go symbol extraction ------------------------------------------------------------------


GO_SOURCE = """\
package main

func Alpha() int {
\treturn 1
}

func (s *Server) Handle() error {
\treturn nil
}

type Config struct {
\tName string
}
"""


@pytest.mark.parametrize(
    ("line", "expected"),
    [(4, ["Alpha"]), (8, ["Server.Handle"]), (12, ["Config"])],
)
def test_go_symbols_covering_a_changed_line(line: int, expected: list[str]) -> None:
    assert go_symbols(GO_SOURCE, {line}) == expected


# --- languages with no extractor -------------------------------------------------------------


def test_symbols_are_null_when_no_language_is_supported(fix_repo: Path, tmp_path: Path) -> None:
    """Null, not empty: the grader redistributes the symbol weight (plan.md section 7.3)."""
    import subprocess

    (fix_repo / "notes.rst").write_text("changed\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(fix_repo), "add", "-A"], check=True, capture_output=True)
    subprocess.run(
        ["git", "-C", str(fix_repo), "commit", "-qm", "docs only"], check=True, capture_output=True
    )

    derived = derive_fix(fix_repo, "HEAD")

    assert derived.files == ["notes.rst"]
    assert derived.symbols is None


# --- writing the result back -----------------------------------------------------------------


GROUND_TRUTH = """\
root_cause: |
  Something went wrong.
component: nova
fix:
  commit: TODO
  url: null
  # files and symbols are generated by `segbench corpus derive`.
  files: []
  symbols: null
provenance: inferred
reviewed_by: null
"""


def test_write_derived_fix_populates_both_fields(tmp_path: Path) -> None:
    path = tmp_path / "ground_truth.yaml"
    path.write_text(GROUND_TRUTH, encoding="utf-8")

    write_derived_fix(path, DerivedFix(commit="abc", files=["a/b.py"], symbols=["C.d"]))

    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert loaded["fix"]["files"] == ["a/b.py"]
    assert loaded["fix"]["symbols"] == ["C.d"]


def test_write_derived_fix_preserves_the_rest_of_the_file(tmp_path: Path) -> None:
    """These files are hand-maintained; a YAML round-trip would silently eat every comment."""
    path = tmp_path / "ground_truth.yaml"
    path.write_text(GROUND_TRUTH, encoding="utf-8")

    write_derived_fix(path, DerivedFix(commit="abc", files=["a/b.py"], symbols=None))

    text = path.read_text(encoding="utf-8")
    assert "# files and symbols are generated" in text
    assert "provenance: inferred" in text
    assert "Something went wrong." in text
    assert yaml.safe_load(text)["fix"]["symbols"] is None


def test_write_derived_fix_is_idempotent(tmp_path: Path) -> None:
    path = tmp_path / "ground_truth.yaml"
    path.write_text(GROUND_TRUTH, encoding="utf-8")
    derived = DerivedFix(commit="abc", files=["a/b.py", "c/d.py"], symbols=["E.f"])

    write_derived_fix(path, derived)
    once = path.read_text(encoding="utf-8")
    write_derived_fix(path, derived)

    assert path.read_text(encoding="utf-8") == once


def test_write_derived_fix_needs_a_fix_block(tmp_path: Path) -> None:
    path = tmp_path / "ground_truth.yaml"
    path.write_text("component: nova\n", encoding="utf-8")

    with pytest.raises(DeriveError, match="no top-level 'fix:' block"):
        write_derived_fix(path, DerivedFix(commit="abc", files=[], symbols=None))
